variable "aws_region" {
  description = "AWS region for the disposable DocuLens demo stack."
  type        = string
  default     = "us-east-1"
}

variable "name_prefix" {
  description = "Name prefix for AWS demo resources."
  type        = string
  default     = "doculens-demo"
}

variable "image_uri" {
  description = "Prebuilt DocuLens app image URI. Build Dockerfile.aws and push it to ECR or another registry before apply."
  type        = string
}

variable "desired_count" {
  description = "Fargate desired task count for the bounded demo."
  type        = number
  default     = 1
}

variable "task_cpu" {
  description = "Fargate task CPU units."
  type        = number
  default     = 512
}

variable "task_memory" {
  description = "Fargate task memory MiB."
  type        = number
  default     = 1024
}

variable "db_allocated_storage" {
  description = "RDS PostgreSQL storage in GiB."
  type        = number
  default     = 20
}

variable "db_instance_class" {
  description = "Small single-AZ RDS instance class for the demo."
  type        = string
  default     = "db.t4g.micro"
}

variable "database_name" {
  description = "Application database name."
  type        = string
  default     = "doculens"
}

variable "database_username" {
  description = "RDS master username. The password is generated by RDS managed master user secret, not Terraform."
  type        = string
  default     = "doculens"
}

variable "database_url_secret_arn" {
  description = "Optional externally populated Secrets Manager ARN whose value is the app DATABASE_URL. Defaults to an empty secret container this stack creates for operators to populate outside Terraform."
  type        = string
  default     = null
  sensitive   = true
}

variable "jwt_secret_arn" {
  description = "Optional externally populated Secrets Manager ARN whose value is JWT_SECRET. Defaults to an empty secret container this stack creates for operators to populate outside Terraform."
  type        = string
  default     = null
  sensitive   = true
}

variable "minimax_api_key_secret_arn" {
  description = "Optional externally populated Secrets Manager ARN whose value is MINIMAX_API_KEY. Defaults to an empty secret container this stack creates for operators to populate outside Terraform."
  type        = string
  default     = null
  sensitive   = true
}
